const data = {
  products: [
    {
      name: 'Free shirt',
      slug: 'free=shirt',
      category: 'shirts',
      image: '/images/shirt1.jpg',
      price: 1200,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 8,
      countInStock: 20,
      decription: 'A popular shirt',
    },
    {
      name: 'Fit shirt',
      slug: 'fit-shirt',
      category: 'shirts',
      image: '/images/shirt2.jpg',
      price: 1400,
      brand: 'Puma',
      rating: '3.9',
      numReviews: 10,
      countInStock: 20,
      decription: 'slim and fit T-shirts for the men',
    },
    {
      name: 'Gym shirt',
      slug: 'gym-shirt',
      category: 'shirts',
      image: '/images/shirt3.jpg',
      price: 1500,
      brand: 'Adidas',
      numReviews: 3,
      countInStock: 30,
      decription: 'Gym shirt with nice fitting',
    },
    {
      name: 'Gym Trouser',
      slug: 'gym-trouser',
      category: 'trousers',
      image: '/images/trouser1.jpg',
      price: 1400,
      brand: 'Adidas',
      numReviews: 4,
      countInStock: 20,
      decription: 'Full fitting gym trouser',
    },
    {
      name: 'Fit Trouser',
      slug: 'fit-trouser',
      category: 'trousers',
      image: '/images/trouser2.jpg',
      price: 1400,
      brand: 'Puma',
      numReviews: 30,
      countInStock: 20,
      description: 'Fit trouser for the men',
    },
  ],
};

export default data;
