import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

export default function Layout({ title, children }) {
  return (
    <div>
      <Head>
        <title> {title ? `${title}-yourShop` : 'yourShop'} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen justify-between flex-col">
        <header>
          <nav className="flex justify-between h-12  shadow-md items-center">
            <Link className="text-lg font-bold" href={'/'}>
              yourShop
            </Link>
            <div>
              <Link className="p-2" href={'/'}>
                {' '}
                Cart
              </Link>
              <Link className="p-2" href={'/'}>
                {' '}
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer>footer</footer>
      </div>
    </div>
  );
}
